name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - main
      - docker-build # Trigger when pushing to 'docker-build' branch
    paths:
      - 'application/**'
      - 'Dockerfile.patient'
      - 'Dockerfile.appointment'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ACCOUNT_ID: ${{ secrets.ECR_ACCOUNT_ID }}
      PATIENT_REPO: patient-service
      APPOINTMENT_REPO: appointment-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and Push Patient Image
        run: |
          docker build -t $PATIENT_REPO ./application/patient
          docker tag $PATIENT_REPO:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PATIENT_REPO:latest
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PATIENT_REPO:latest

      - name: Build and Push Appointment Image
        run: |
          docker build -t $APPOINTMENT_REPO ./application/appointment
          docker tag $APPOINTMENT_REPO:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APPOINTMENT_REPO:latest
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$APPOINTMENT_REPO:latest
