name: Deploy AWS Infrastructure and ECS Services

on:
  push:
    branches:
      - main
      - infra  # Trigger when pushing to 'infra' branch
    paths:
      - 'terraform/**' # Only trigger if Terraform files are modified

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ACCOUNT_ID: ${{ secrets.ECR_ACCOUNT_ID }}
      PATIENT_REPO: patient-service
      APPOINTMENT_REPO: appointment-service
      VPC_ID: ${{ secrets.VPC_ID }}
      SUBNET_IDS: ${{ secrets.SUBNET_IDS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ECS Infrastructure with Terraform
        run: |
          terraform init
          terraform apply -var="vpc_id=$VPC_ID" -var="subnet_ids=$SUBNET_IDS" -auto-approve
