name: Deploy AWS Infrastructure and ECS Services

on:
  push:
    branches:
      - main  # Trigger when pushing to 'infra' branch
    paths:
      - 'terraform/**' # Only trigger if Terraform files are modified

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ACCOUNT_ID: ${{ secrets.ECR_ACCOUNT_ID }}
      PATIENT_REPO: dev/bayer/patient
      APPOINTMENT_REPO: dev/bayer/appointment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy ECS Infrastructure with Terraform
        run: |
          terraform init -backend-config=backend-dev.hcl
          terraform plan -var-file="dev.tfvars"
          terraform apply -var-file="dev.tfvars" -auto-approve
